
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Apr 29 13:22:50 CEST 2021
//----------------------------------------------------

package analizador.sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ASTERISCO = 7;
  public static final int ALTER = 6;
  public static final int SIM = 16;
  public static final int CORCIE = 13;
  public static final int CORAP = 12;
  public static final int PCIE = 11;
  public static final int PAP = 10;
  public static final int ESCAPESIM = 15;
  public static final int EOF = 0;
  public static final int MAS = 8;
  public static final int VAR = 4;
  public static final int GUION = 14;
  public static final int INTERR = 9;
  public static final int IGUAL = 3;
  public static final int error = 1;
  public static final int AUX = 2;
  public static final int DEF = 5;
}

